collections:
  posts:
    permalink: /blog/:year/:month/:day/:title
    output: true
  updates:
    permalink: /updates/:year/:month/:day
    output: true
  testimonials:
    output: false

github_repo_root: https://github.com/appveyor/website/tree/master/NJekyll/site
google_analytics_id: UA-32029905-1

redirects:
  /2014/11/13/appveyor-premium-build-environment-and-new-pricing: /blog/2014/11/13/appveyor-premium-build-environment-and-new-pricing
  /2014/11/06/appveyor-with-a-hint-of-chocolatey: /blog/2014/11/06/appveyor-with-a-hint-of-chocolatey
  /2014/07/23/appveyor-yml-and-multiple-branches: /blog/2014/07/23/appveyor-yml-and-multiple-branches
  /2014/06/04/shallow-clone-for-git-repositories: /blog/2014/06/04/shallow-clone-for-git-repositories
  /2014/04/23/build-worker-improvements: /blog/2014/04/23/build-worker-improvements
  /2014/03/31/web-deploy-parametrization-in-appveyor-ci: /blog/2014/03/31/web-deploy-parametrization-in-appveyor-ci
  /2014/03/26/appveyor-20-goes-live-with-a-new-pricing: /blog/2014/03/26/appveyor-20-goes-live-with-a-new-pricing
  /2014/03/25/continuous-delivery-of-windows-azure-cloud-services-with-appveyor-ci: /blog/2014/03/25/continuous-delivery-of-windows-azure-cloud-services-with-appveyor-ci
  /2014/03/18/about-nuget-package-restore: /blog/2014/03/18/about-nuget-package-restore
  /2014/02/23/converting-mercurial-repository-to-git-on-windows: /blog/2014/02/23/converting-mercurial-repository-to-git-on-windows
  /2014/02/21/nuget-support-in-appveyor-ci: /blog/2014/02/21/nuget-support-in-appveyor-ci
  /2014/02/19/appveyor-20-dedicated-build-vms-parallel-testing-nuget-deployment: /blog/2014/02/19/appveyor-20-dedicated-build-vms-parallel-testing-nuget-deployment
  /2013/10/01/appveyor-ci-overview-presentation: /blog/2013/10/01/appveyor-ci-overview-presentation
  /2013/09/25/appveyor-update-and-new-pricing: /blog/2013/09/25/appveyor-update-and-new-pricing
  /2013/07/08/appveyor-github-integration-and-build-process-improvements: /blog/2013/07/08/appveyor-github-integration-and-build-process-improvements
  /2013/06/14/welcome-to-appveyor-ci-beta: /blog/2013/06/14/welcome-to-appveyor-ci-beta
